### ISSUE TITLE
IllegalState Failed to load ApplicationCo...

### ISSUE THREAD

**Issue by sidalidev** [gustavoponce7/spring-login#1]
```[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 3.809 s <<< FAILURE! - in com.gpch.login.LoginApplicationTests
[ERROR] contextLoads(com.gpch.login.LoginApplicationTests)  Time elapsed: 0.001 s  <<< ERROR!
java.lang.IllegalStateException: Failed to load ApplicationContext
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'entityManagerFactory' defined in class path resource [org/springframework/boot/autoconfigure/orm/jpa/HibernateJpaConfiguration.class]: Invocation of init method failed; nested exception is java.lang.NoClassDefFoundError: javax/xml/bind/JAXBException
Caused by: java.lang.NoClassDefFoundError: javax/xml/bind/JAXBException
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.JAXBException

[INFO] Running com.gpch.login.service.UserServiceTest
[ERROR] Tests run: 2, Failures: 0, Errors: 2, Skipped: 0, Time elapsed: 0.104 s <<< FAILURE! - in com.gpch.login.service.UserServiceTest
[ERROR] testSaveUser(com.gpch.login.service.UserServiceTest)  Time elapsed: 0.041 s  <<< ERROR!
org.mockito.exceptions.base.MockitoException:

Mockito cannot mock this class: interface com.gpch.login.repository.UserRepository.

Mockito can only mock non-private & non-final classes.
If you're not sure why you're getting this error, please report to the mailing list.


Java               : 11
JVM vendor name    : Oracle Corporation
JVM vendor version : 11.0.1+13-LTS
JVM name           : Java HotSpot(TM) 64-Bit Server VM
JVM version        : 11.0.1+13-LTS
JVM info           : mixed mode
OS name            : Mac OS X
OS version         : 10.14.1


Underlying exception : java.lang.UnsupportedOperationException: Cannot define class using reflection
	at com.gpch.login.service.UserServiceTest.setUp(UserServiceTest.java:31)
Caused by: java.lang.UnsupportedOperationException: Cannot define class using reflection
	at com.gpch.login.service.UserServiceTest.setUp(UserServiceTest.java:31)
Caused by: java.lang.IllegalStateException: Could not find sun.misc.Unsafe
	at com.gpch.login.service.UserServiceTest.setUp(UserServiceTest.java:31)
Caused by: java.lang.NoSuchMethodException: sun.misc.Unsafe.defineClass(java.lang.String, [B, int, int, java.lang.ClassLoader, java.security.ProtectionDomain)
	at com.gpch.login.service.UserServiceTest.setUp(UserServiceTest.java:31)

[ERROR] testFindUserByEmail(com.gpch.login.service.UserServiceTest)  Time elapsed: 0.062 s  <<< ERROR!
org.mockito.exceptions.base.MockitoException:

Mockito cannot mock this class: interface com.gpch.login.repository.UserRepository.

Mockito can only mock non-private & non-final classes.
If you're not sure why you're getting this error, please report to the mailing list.


Java               : 11
JVM vendor name    : Oracle Corporation
JVM vendor version : 11.0.1+13-LTS
JVM name           : Java HotSpot(TM) 64-Bit Server VM
JVM version        : 11.0.1+13-LTS
JVM info           : mixed mode
OS name            : Mac OS X
OS version         : 10.14.1


Underlying exception : java.lang.UnsupportedOperationException: Cannot define class using reflection
	at com.gpch.login.service.UserServiceTest.setUp(UserServiceTest.java:31)
Caused by: java.lang.UnsupportedOperationException: Cannot define class using reflection
	at com.gpch.login.service.UserServiceTest.setUp(UserServiceTest.java:31)
Caused by: java.lang.IllegalStateException: Could not find sun.misc.Unsafe
	at com.gpch.login.service.UserServiceTest.setUp(UserServiceTest.java:31)
Caused by: java.lang.NoSuchMethodException: sun.misc.Unsafe.defineClass(java.lang.String, [B, int, int, java.lang.ClassLoader, java.security.ProtectionDomain)
	at com.gpch.login.service.UserServiceTest.setUp(UserServiceTest.java:31)

[INFO]
[INFO] Results:
[INFO]
[ERROR] Errors:
[ERROR]   LoginApplicationTests.contextLoads » IllegalState Failed to load ApplicationCo...
[ERROR]   UserServiceTest.setUp:31 Mockito
Mockito cannot mock this class: interface co...
[ERROR]   UserServiceTest.setUp:31 Mockito
Mockito cannot mock this class: interface co...
[INFO]
[ERROR] Tests run: 3, Failures: 0, Errors: 3, Skipped: 0
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  05:46 min
[INFO] Finished at: 2018-11-29T13:03:32+01:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.21.0:test (default-test) on project login: There are test failures.
[ERROR]
[ERROR] Please refer to /Users/sid/Documents/university/intergiciel/tutorial-example/spring-login/target/surefire-reports for the individual test results.
[ERROR] Please refer to dump files (if any exist) [date]-jvmRun[N].dump, [date].dumpstream and [date]-jvmRun[N].dumpstream.
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException```

**Comment by tbago** [comment]
I have the same issue.

**Comment by Nihalh55** [comment]
I have the same Issue. Please help

**Comment by gustavoponce7** [comment]
Please fetch the latest changes, the issue has been resolved
